 const messages = [
    {"value":"Que você seja presenteado com as maiores alegrias da vida e felicidade sem fim. Afinal, você mesmo é um presente para a terra, então merece o melhor!"},
    {"value":"Não conte as velas... veja as luzes que elas fornecem. Não conte os anos, mas a vida que você vive. Desejando-lhe um tempo maravilhoso pela frente!" }, 
    {"value":"Esqueça o passado; olhe para o futuro, pois as melhores coisas ainda estão por vir!"},
    {"value":"Você é jovem apenas uma vez, mas pode ser imaturo por toda a vida!"},
    {"value":"Felicidades para você para outra viagem ao redor do sol!"},
    {"value":"Desejo-lhe um lindo dia com muita saúde e felicidade para sempre."},
    {"value":"Não se esqueça de sorrir sem jeito enquanto todos cantam parabéns para você hoje!"},
    {"value":"Aniversários são a maneira da natureza nos dizer para comer mais bolo!"},
    {"value":"No seu aniversário, vou compartilhar o segredo para permanecer jovem: minta sobre sua idade."},
    {"value":"Trabalhar duro. Viver intensamente. Coma muito bolo. Esse é um bom lema para o seu aniversário e para a vida."},
    {"value":"Espero que você receba dezenas de presentes de aniversário!"},
    {"value":"Que você tenha todo o amor que seu coração pode conter, toda a felicidade que um dia pode trazer e todas as bênçãos que uma vida pode revelar."},
    {"value":"Seja feliz! Hoje é o dia em que você veio a este mundo para ser uma bênção e inspiração para as pessoas ao seu redor! Você é uma pessoa maravilhosa! Que você receba mais aniversários para realizar todos os seus sonhos!"},
    {"value":"Esqueça o passado, você não pode mudá-lo. Esqueça o futuro, você não pode prevê-lo. E esqueça o presente, não comprei um para você. Feliz aniversário!"},
    {"value":"Conforme você envelhece, três coisas acontecem. A primeira é que sua memória falha, e não consigo me lembrar das outras duas. Feliz aniversário!"},
    {"value":"Quando as crianças perguntarem quantos anos você tem na sua festa, você deve ir em frente e contar a elas. Enquanto eles estão distraídos tentando contar tão alto, você pode roubar um pedaço do bolo deles! Feliz aniversário!"},
    {"value":"Enviando-lhe sorrisos para cada momento do seu dia especial…Tenha um tempo maravilhoso e um feliz aniversário!"},
    {"value":"Enviando-lhe um desejo de aniversário embrulhado com todo o meu amor. Tenha Um Feliz Aniversário!"},
    {"value":"Uma comemoração simples, uma reunião de amigos; aqui desejando-lhe muitas felicidades e uma alegria que nunca acaba. Feliz aniversário!"},
    {"value":"Espero que seu aniversário seja como você ... totalmente incrível."},
    {"value":"Espero que hoje, na sua festa, você dance e os outros cantem enquanto você comemora com alegria o seu melhor aniversário."},
    {"value":"É sempre um prazer desejar feliz aniversário a alguém tão querido."},
    {"value":"Ei você! É seu aniversário! Bolo! Velas! Bebidas! Presentes! Mais comida! Você pode dizer que estou animado?"},
    {"value":"Feliz aniversário para meu eterno jovem amigo!"},
    {"value":"Os aniversários acontecem apenas uma vez por ano, e sua amizade só acontece uma vez na vida."},
    {"value":"Você merece todo o bolo, felicidade e amor hoje. Feliz aniversário!"},
    {"value":"Obrigado por ser a pessoa mais brilhante que conheço. Espero vê-lo brilhar por muitos anos! Feliz aniversário!"},
]

export default messages;

